table FactSurveyResponse
	lineageTag: fd0edb52-171b-4150-b0e5-fc932cb2f50f

	column SurveyResponseKey
		dataType: int64
		formatString: 0
		lineageTag: 9670c8ce-cfb4-4f09-80d0-c5417845ee8d
		summarizeBy: count
		sourceColumn: SurveyResponseKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 755b32fe-eebf-4ccf-97f4-cac4bd4c0ba9
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 2a3f66d0-7a92-4c7d-9467-188f6f27b3ee
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 45599ba4-6feb-46a0-bf60-c83da8dca17f
		summarizeBy: count
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductCategoryName
		dataType: string
		lineageTag: d4176138-be31-4954-8228-2c0fb831d090
		summarizeBy: none
		sourceColumn: EnglishProductCategoryName

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: c1e89a7e-d5c9-4a9c-86f0-fb4ad3e9ab35
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductSubcategoryName
		dataType: string
		lineageTag: 6e78bf2f-608c-4e75-8622-70aff6d9d9f7
		summarizeBy: none
		sourceColumn: EnglishProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dea1e0af-5021-468a-9afb-8f53347f7080
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition FactSurveyResponse = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost", "AdventureWorksDW2022"),
				    dbo_FactSurveyResponse = Source{[Schema="dbo",Item="FactSurveyResponse"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_FactSurveyResponse,{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

