table FactInternetSales
	lineageTag: 91c67982-4d64-4f7b-b8d1-26654d084cea

	measure SaleAmount = ```
			SUM(FactInternetSales[SalesAmount]) 
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 688b55b1-6c69-41c6-a324-ec62b97c5a1a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Stars = ```
			
			// svg essentials
			VAR svg_start = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 500 100'>"
			VAR svg_end = "</svg>"
			
			// star shape
			VAR Star1 = "<path d='m50,2 12,34h36l-28,22 10,34-30-20-30,20 10-34-28-22h36z'/>"
			
			// logic based on SaleAmount
			VAR SaleAmount = [SaleAmount] // Replace with your actual measure/column
			VAR StarCount = 
			    SWITCH(
			        TRUE(),
			        SaleAmount < 10000, 1,
			        SaleAmount < 100000, 2,
			        SaleAmount < 1000000, 3,
			        SaleAmount < 5000000, 4,
			        5
			    )
			
			// generate stars
			VAR StarPositions = CONCATENATEX(
			    GENERATESERIES(0, (StarCount - 1) * 100, 100),
			    "<g transform='translate(" & [Value] & ",0)'>" & Star1 & "</g>"
			)
			
			// Coloured Stars
			VAR GreyStars = "<g fill='White' stroke-width='1' stroke='Black'>" & StarPositions & "</g>"
			VAR GoldStars = "<g fill='Gold'>" & StarPositions & "</g>"
			
			// combine SVG
			RETURN
			    svg_start & GreyStars & GoldStars & svg_end
			
			```
		lineageTag: e7bb18e1-88ba-4db1-a740-5cfc49eaee1d
		dataCategory: ImageUrl

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 3d675292-2710-48b5-9787-5f5c6fcf3bfd
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 29bb290c-97b5-4a59-a172-2f8293f8cd57
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 3bb1d319-3600-4840-8910-1df2fed0e65c
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 111ef0a3-6697-4273-85fe-3afc7baff52c
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: a4429a78-d6f9-4ea9-af95-30560c05d056
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 48b22f51-e999-4bf6-b2e5-1d35d3c6efbc
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: d0671fee-710a-4777-b4fd-e21c33a386a1
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: d189f6e8-705d-4010-9cc9-571e412d90fb
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 6d75f133-8cd6-4888-8344-f077eea7be1e
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 344042b2-2c5f-4035-8c56-7061e5076fe4
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: ff73ebe2-b318-4138-a6b9-df8e238f8635
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 96a7e92f-51ee-4f8a-92a6-57cd29a849f4
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ab0a0ce7-37fd-4751-bfe8-602687b6a15f
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ExtendedAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 26dabf63-8510-47b8-b37f-2f8033637d62
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: f8d89d16-adc9-4ebf-b102-8fd80851f5be
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 9ed7abc0-1f31-4236-af8b-520a7bb9d35a
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 457eeb9f-0466-4444-b5d9-8e24c8c35e4c
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TotalProductCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b331c109-1aaa-40c3-934a-946654921b4b
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SalesAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d53419a6-0f2c-466b-bcdf-0958a295f5c4
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TaxAmt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 141a9e68-18c9-48ef-8dcb-194e11fa00ff
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Freight
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9c17e7d7-ba31-468f-87bc-5769380b0b76
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column CarrierTrackingNumber
		dataType: string
		lineageTag: 6f939a27-64f6-443d-808d-1d9f4bc5db1f
		summarizeBy: none
		sourceColumn: CarrierTrackingNumber

		annotation SummarizationSetBy = Automatic

	column CustomerPONumber
		dataType: string
		lineageTag: 85944913-a5e5-4792-adb8-dd51e615f1b5
		summarizeBy: none
		sourceColumn: CustomerPONumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 43499a7c-3acf-4eba-9b79-5a89dedbde78
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7989c99a-9cff-422d-a658-bb8224318979
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: d459c2da-6149-4222-9dce-ed40a3e43cca
			defaultHierarchy: LocalDateTable_82854982-aa90-4899-9b70-e9bce3dcea41.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: d7a5783c-1ef4-4d16-a144-a9fbbdec195a
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 11e2cba3-8a16-41f0-a88e-4cc2f8605e75
			defaultHierarchy: LocalDateTable_328cbfee-3f10-4653-b093-369ebd4e7ab6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition FactInternetSales = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost", "AdventureWorksDW2022"),
				    dbo_FactInternetSales = Source{[Schema="dbo",Item="FactInternetSales"]}[Data]
				in
				    dbo_FactInternetSales

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

