table DimProduct
	lineageTag: 6e041916-2e0d-49bf-b47b-934576cfc204

	measure DynamicHeartSVG = ```
			
			VAR FillColor = SELECTEDVALUE(DimProduct[Color], "red")
			RETURN
			"data:image/svg+xml;utf8,<svg width='100' height='100' xmlns='http://www.w3.org/2000/svg'><path d='M50 30 C30 10, 10 30, 50 70 C90 30, 70 10, 50 30' fill='" & FillColor & "' stroke='black' stroke-width='2'/></svg>"
			
			```
		lineageTag: 548d68c4-7133-4d09-bc56-cf584673f834
		dataCategory: ImageUrl

	measure StarSVG = ```
			
			VAR FillColor = SELECTEDVALUE(DimProduct[Color], "#EFCE4A") -- Default color is #EFCE4A
			RETURN
			"data:image/svg+xml;utf8,<?xml version='1.0' encoding='iso-8859-1'?>
			<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
			<svg height='800px' width='800px' version='1.1' id='Capa_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' 
				 viewBox='0 0 53 53' xml:space='preserve'>
			<path style='fill:" & FillColor & ";' d='M26.5,9c-8.837,0-16,7.164-16,16c0,7.089,4.615,13.091,11,15.192V50h2v3h6v-3h2v-9.808
				c6.385-2.101,11-8.103,11-15.192C42.5,16.164,35.337,9,26.5,9z'/>
			<g>
				<path style='fill:" & FillColor & ";' d='M26.5,0c-0.553,0-1,0.447-1,1v4c0,0.553,0.447,1,1,1s1-0.447,1-1V1C27.5,0.447,27.053,0,26.5,0z'/>
				<path style='fill:" & FillColor & ";' d='M50.5,24h-4c-0.553,0-1,0.447-1,1s0.447,1,1,1h4c0.553,0,1-0.447,1-1S51.053,24,50.5,24z'/>
				<path style='fill:" & FillColor & ";' d='M6.5,24h-4c-0.553,0-1,0.447-1,1s0.447,1,1,1h4c0.553,0,1-0.447,1-1S7.053,24,6.5,24z'/>
				<path style='fill:" & FillColor & ";' d='M42.764,7.322l-2.828,2.828c-0.391,0.391-0.391,1.023,0,1.414c0.195,0.195,0.451,0.293,0.707,0.293
					s0.512-0.098,0.707-0.293l2.828-2.828c0.391-0.391,0.391-1.023,0-1.414S43.154,6.932,42.764,7.322z'/>
				<path style='fill:" & FillColor & ";' d='M11.65,38.436l-2.828,2.828c-0.391,0.391-0.391,1.023,0,1.414c0.195,0.195,0.451,0.293,0.707,0.293
					s0.512-0.098,0.707-0.293l2.828-2.828c0.391-0.391,0.391-1.023,0-1.414S12.041,38.045,11.65,38.436z'/>
				<path style='fill:" & FillColor & ";' d='M41.35,38.436c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414l2.828,2.828
					c0.195,0.195,0.451,0.293,0.707,0.293s0.512-0.098,0.707-0.293c0.391-0.391,0.391-1.023,0-1.414L41.35,38.436z'/>
				<path style='fill:" & FillColor & ";' d='M10.236,7.322c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414l2.828,2.828
					c0.195,0.195,0.451,0.293,0.707,0.293s0.512-0.098,0.707-0.293c0.391-0.391,0.391-1.023,0-1.414L10.236,7.322z'/>
			</g>
			<path style='fill:#F7E6A1;' d='M15.5,26c-0.553,0-1-0.447-1-1c0-6.617,5.383-12,12-12c0.553,0,1,0.447,1,1s-0.447,1-1,1
				c-5.514,0-10,4.486-10,10C16.5,25.553,16.053,26,15.5,26z'/>
			<polygon style='fill:#556080;' points='21.5,43 21.5,50 23.5,50 23.5,53 29.5,53 29.5,50 31.5,50 31.5,43 '/>
			</svg>"
			
			```
		lineageTag: 809c8242-7f3c-4fc7-9742-095df0841c16
		dataCategory: ImageUrl

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 35e5ece4-5daa-409e-b4da-cc058d048fbb
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductAlternateKey
		dataType: string
		lineageTag: abc30e63-9664-461e-b6f4-01c1f2758be7
		summarizeBy: none
		sourceColumn: ProductAlternateKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: c1d699cb-bf8f-4dcc-b595-837f43c793d3
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column WeightUnitMeasureCode
		dataType: string
		lineageTag: 27840498-1503-476f-bc83-08b4bacd4593
		summarizeBy: none
		sourceColumn: WeightUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column SizeUnitMeasureCode
		dataType: string
		lineageTag: c41cf90c-ebb1-4214-bfb6-99046616de27
		summarizeBy: none
		sourceColumn: SizeUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column EnglishProductName
		dataType: string
		lineageTag: a9e5c7ca-3df5-42d3-934a-04923b189f83
		summarizeBy: none
		sourceColumn: EnglishProductName

		annotation SummarizationSetBy = Automatic

	column SpanishProductName
		dataType: string
		lineageTag: ccc5768b-2135-4c92-994b-782d2556791d
		summarizeBy: none
		sourceColumn: SpanishProductName

		annotation SummarizationSetBy = Automatic

	column FrenchProductName
		dataType: string
		lineageTag: 135d23ff-ca46-4955-9ebc-5c95f97a82f6
		summarizeBy: none
		sourceColumn: FrenchProductName

		annotation SummarizationSetBy = Automatic

	column StandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a3d050db-8c97-4119-8c15-be44f9511886
		summarizeBy: sum
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column FinishedGoodsFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a32c8a0-c8b3-4f87-9a37-d582b8798242
		summarizeBy: none
		sourceColumn: FinishedGoodsFlag

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 79f40289-1a14-4a79-bbd6-466f29ec5659
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column SafetyStockLevel
		dataType: int64
		formatString: 0
		lineageTag: b00ff7cf-f933-45c1-8d32-d882f0904c30
		summarizeBy: sum
		sourceColumn: SafetyStockLevel

		annotation SummarizationSetBy = Automatic

	column ReorderPoint
		dataType: int64
		formatString: 0
		lineageTag: 0ee55559-afba-4407-8484-5c541e05f72c
		summarizeBy: sum
		sourceColumn: ReorderPoint

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4be03257-7ec8-4999-8c61-ef0ddb0ca5eb
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Size
		dataType: string
		lineageTag: adf65329-4290-487a-ac05-465c8c08b184
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column SizeRange
		dataType: string
		lineageTag: 0d4e27f2-3ee7-47ca-9efe-d0c141a3a736
		summarizeBy: none
		sourceColumn: SizeRange

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 67ff32a5-707f-41d4-af46-2e72d05717ac
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DaysToManufacture
		dataType: int64
		formatString: 0
		lineageTag: 11b89f2b-7e49-42c9-b53c-0fb4796a6ff0
		summarizeBy: sum
		sourceColumn: DaysToManufacture

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 6b484aff-de2c-4e95-822d-9de3cd125f0a
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column DealerPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 920b52cd-b1ac-47e6-b723-05b49fb84506
		summarizeBy: sum
		sourceColumn: DealerPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Class
		dataType: string
		lineageTag: 35500faf-cd7f-4784-9439-bc8d0163a1f0
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: d4c90125-b26c-4844-ae36-6ea9d6bb4034
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: faccecf6-d5be-463c-af5c-d62d8fd1921c
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column EnglishDescription
		dataType: string
		lineageTag: 9bfd5f0c-50f1-4bd8-9bc0-f9ca6f772b13
		summarizeBy: none
		sourceColumn: EnglishDescription

		annotation SummarizationSetBy = Automatic

	column FrenchDescription
		dataType: string
		lineageTag: 38cd0c96-6e0a-46fe-abac-749085fcdad2
		summarizeBy: none
		sourceColumn: FrenchDescription

		annotation SummarizationSetBy = Automatic

	column ChineseDescription
		dataType: string
		lineageTag: 83e5afa2-aa4f-47c5-9fa5-f92c0d188764
		summarizeBy: none
		sourceColumn: ChineseDescription

		annotation SummarizationSetBy = Automatic

	column ArabicDescription
		dataType: string
		lineageTag: c0b55732-256b-405a-bb14-ffaf84409bb4
		summarizeBy: none
		sourceColumn: ArabicDescription

		annotation SummarizationSetBy = Automatic

	column HebrewDescription
		dataType: string
		lineageTag: 89cd2cd7-c3ed-46e4-b885-565d3b3ad3d7
		summarizeBy: none
		sourceColumn: HebrewDescription

		annotation SummarizationSetBy = Automatic

	column ThaiDescription
		dataType: string
		lineageTag: 62c31ab0-cc79-4c16-842f-4fa3ea56f546
		summarizeBy: none
		sourceColumn: ThaiDescription

		annotation SummarizationSetBy = Automatic

	column GermanDescription
		dataType: string
		lineageTag: d1505405-ac6f-4a31-99cc-d47562128d13
		summarizeBy: none
		sourceColumn: GermanDescription

		annotation SummarizationSetBy = Automatic

	column JapaneseDescription
		dataType: string
		lineageTag: c7aef1e9-66d3-4ebe-80cf-e6d4fddf6724
		summarizeBy: none
		sourceColumn: JapaneseDescription

		annotation SummarizationSetBy = Automatic

	column TurkishDescription
		dataType: string
		lineageTag: 3c04037e-4d4f-42ec-8034-567b34bf46ae
		summarizeBy: none
		sourceColumn: TurkishDescription

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a9e922c-29b5-4d2e-9abf-6785569430d9
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 70efe661-d955-4521-bb5e-9d58ce518ab7
			defaultHierarchy: LocalDateTable_fd95f4ac-c028-448e-a78b-5316d67bc7b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: f2d94d0c-c7f6-4dd5-937f-dddac14370bb
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: 8a37a287-9ca3-4032-b9c8-5dc0aa4c8a9e
			defaultHierarchy: LocalDateTable_7df8753f-d509-48fb-a5bd-84ab75b4b5b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: c8f44e03-d6eb-424d-9bb7-b408619d68a8
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost", "AdventureWorksDW2022"),
				    dbo_DimProduct = Source{[Schema="dbo",Item="DimProduct"]}[Data]
				in
				    dbo_DimProduct

	annotation PBI_ResultType = Table

